# Default configuration

cloud: local

alerts:
  enabled: false

debug: false

ingress:
  enabled: false

database:
  host: localhost
  port: 5432
  credentials:
    username: dev
    password: dev

replicas: 1

host: '${ENV}.trumid.com'

tls:
  enabled: false

resources:
  memory: 128Mi
  cpu: 1
